version: "3.9"

services:
  paper-server:
    container_name: "paper-server"
    image: "docker-paper-server"
    networks:
      - mc
    tty: true
    privileged: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./plugins:/opt/server/plugins
      - ./worlds:/opt/server/worlds

networks:
  mc:
    external: true
